# fly.toml app configuration file generated for full-stack-open-pokedex-polished-lake-1770 on 2025-06-14T10:00:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
[env]
  PORT = "3000"

[processes]
  app = "node app.js"


app = 'full-stack-open-pokedex-polished-lake-1770'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'true'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
