name: simple-deployment-pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: build executable
        run: npm run build

      - name: test file
        run: npm run test

      - name: end-to-end test
        run: npm run test:e2e

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Notify Discord
        if: ${{ success() }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"Deployment succeeded on main!"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Notify Discord on failure
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Deployment Failed!"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
               
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch